/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xbwkreeloqblupyvetmm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhid2tyZWVsb3FibHVweXZldG1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk3NTk4NjEsImV4cCI6MjA3NTMzNTg2MX0.JWzzIC-NIiOonZEIcjZfRfIDbStztx4s9EOD-nBXwyI"